# Generated by Django 4.2.15 on 2024-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apMaternoCliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apPaternoCliente',
            field=models.CharField(max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celularCliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccionCliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dvRutCliente',
            field=models.CharField(max_length=1, verbose_name='Digito Verificador'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='emailCliente',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rutCliente',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefonoCliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
