# Generated by Django 4.2.15 on 2024-10-19 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='rutAdministrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optica.administrador', verbose_name='RUN Administrador'),
        ),
    ]
