# Generated by Django 4.2.15 on 2024-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0002_alter_cliente_apmaternocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='observacionOrdenTrabajo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='apMaternoCliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='receta',
            name='apPaternoCliente',
            field=models.CharField(max_length=20, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='receta',
            name='celularCliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='receta',
            name='dvRutCliente',
            field=models.CharField(max_length=1, null=True, verbose_name='Digito Verificador'),
        ),
        migrations.AddField(
            model_name='receta',
            name='nombreCliente',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='receta',
            name='observacionReceta',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='receta',
            name='telefonoCliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rutCliente',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='RUN'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cercaOd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cerca OD'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cercaOi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cerca OI'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='doctorOftalmologo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tecnologo Oftalmologia'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dpCerca',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='DP Cerca'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dpLejos',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='DP Lejos'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fechaReceta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='institucion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Institucion'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='lejosOd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Lejos OD'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='lejosOi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Lejos OI'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='numeroReceta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipoLente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Lente'),
        ),
    ]
