# Generated by Django 4.2.15 on 2024-11-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0002_alter_ordentrabajo_idreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipoPago',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Tipo de Pago'),
        ),
    ]
