# Generated by Django 4.2.15 on 2024-10-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0004_alter_receta_apmaternocliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='apMaternoCliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='apPaternoCliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='celularCliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dvRutCliente',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Digito Verificador'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombreCliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='telefonoCliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
