# Generated by Django 4.2.15 on 2024-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0005_alter_receta_apmaternocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagenReceta',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
