# Generated by Django 4.2.15 on 2024-10-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0007_alter_receta_imagenreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagenReceta',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
