# Generated by Django 4.2.15 on 2024-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0008_alter_receta_imagenreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagenReceta',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
